# Generated by Django 5.1.4 on 2025-06-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('voter', 'Voter'), ('auditor', 'Auditor')], default='voter', max_length=10),
        ),
    ]
