# Generated by Django 5.2.3 on 2025-06-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_election_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('voter', 'Voter'), ('auditor', 'Auditor')], default='voter', max_length=10),
        ),
    ]
